version: '3.9'

services:
  # MongoDB services
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db

  # Node API services
  api:
    container_name: flexmotos_api
    build: ./backend
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: flexmotos_db
      NAME: FlexMotos
      FRONTEND_URI: http://191.101.78.114:3001
    depends_on:
      - mongo_db

  # Next.js app
  web:
    container_name: flexmotos_web
    build: ./frontend
    ports:
      - 3001:3001
    depends_on:
      - api

volumes:
  mongo_db: {}
