version: '3.9'

services:
  # Node API services
  api:
    container_name: flexmotos_api
    build: ./backend
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://localhost:27017
      DB_NAME: flexmotos_db
      NAME: FlexMotos
      FRONTEND_URI: http://flexmotosoficial.com.br

  # Next.js app
  web:
    container_name: flexmotos_web
    build: ./frontend
    ports:
      - 3001:3001
    depends_on:
      - api

volumes:
  mongo_db: {}
