version: '3'

services:
  frontend:
    build: ./frontend
    command: npm start
    ports:
      - "3000:3000"
    depends_on:
      - "backend"

  backend:
    build: ./backend
    command: npm start
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/usr/app
    depends_on:
      - "mongo"

  mongo:
    image: mongo
    restart: always
    ports:
      - "3002:27017"

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
